#### Blóðflokkur:

-Einstaklingur í blóðflokki O einungis þegið nýra frá einstaklingi í blóðflokki O  
-Einstaklingur í blóðflokki A einungis þegið nýra frá einstaklingi í blóðflokki O eða A  
-Einstaklingur í blóðflokki B einungis þegið nýra frá einstaklingi í blóðflokki O eða B  
-Einstaklingur í blóðflokki AB einungis þegið nýra frá einstaklingi í blóðflokki O, B eða A  

Ekki þarf að taka tillit til Rhesus +/- við líffæra ígræðslur

#### HLA mótefnavakar:

HLA Typing
HLA typing is also called “tissue typing”. HLA stands for human leukocyte antigen. Antigens are proteins on the cells in the body. Out of over 100 different antigens that have been identified, there are six that have been shown to be the most important in organ transplantation. Of these six antigens, we inherit three from each parent.

Except in cases of identical twins and some siblings, it is rare to get a six-antigen match between two people, especially if they are unrelated. Kidneys are very successfully transplanted between two people with no matching antigens.

A person can make antibodies against another person’s HLA antigens. Antibodies can result from blood transfusions, pregnancy, infections or even a viral illness. Having one of these events does not mean a person will make antibodies but they could. If a recipient has strong antibodies against a donor’s HLA, the risk of rejection is high and a donor would be declined for that recipient.

HLA-A,HLA-B and HLA-C; minor genes are HLA-E, HLA-F and HLA-G
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3598844/

https://journals.plos.org/plosone/article/file?id=10.1371/journal.pone.0196707&type=printable

In [50]:
import numpy as np
import random

In [4]:
def rand_pop(size):
#--------------------------------------------------------------------------------------------------------------------------
    #Function that creates a random pool of Icelandic people
    
    #Input Variables:
        #size:       Number of persons, int
    
    #Output:
        #pop:        Pool of Icelandic people with and critera used for evaluating kidney compatibility, array
#--------------------------------------------------------------------------------------------------------------------------
    
    bt_pop = np.random.choice(['O', 'A', 'B', 'AB'], size, p=[0.55, 0.32, 0.10, 0.03])
    cig_pop = np.random.choice([0, 1], size, p=[0.855, 0.145])                           #visindavefur.is/svar.php?id=3349
    age_pop = np.random.randint(18, 60 ,size)
    gen_pop = np.random.choice([0, 1], size, p=[0.5, 0.5])
    aa_pop = np.random.choice([0, 1], size, p=[0.98, 0.02])
    rel_pop = np.random.choice([0, 1], size, p=[0.5, 0.5])
    hla_b_pop = np.random.choice([0, 1, 2], size, p=[0.05, 0.30, 0.65])
    hla_dr_pop = np.random.choice([0, 1, 2], size, p=[0.05, 0.30, 0.65])
    
    #Initialize
    eGFR_pop = np.zeros(size)            #kidney.org/sites/default/files/docs/11-10-1813_abe_patbro_gfr_b.pdf
    BMI_pop = np.zeros(size)             #landlaeknir.is/servlet/file/store93/item35880/4950_zbmifl_BMI_UTFEGID.pdf
    SBP_pop = np.zeros(size)             #hjarta.is/wp-content/uploads/2019/03/Handbok-Hjartaverndar.pdf
    
    
    for i in range(size):
        
        if age_pop[i] >= 18 and age_pop[i] <= 29:
            eGFR_pop[i] = 116
        elif age_pop[i] >= 30 and age_pop[i] <= 39:
            eGFR_pop[i] = 107
        elif age_pop[i] >= 40 and age_pop[i] <= 49:
            eGFR_pop[i] = 99
        elif age_pop[i] >= 50 and age_pop[i] <= 59:
            eGFR_pop[i] = 93
        elif age_pop[i] >= 60 and age_pop[i] <= 69:
            eGFR_pop[i] = 85
        elif age_pop[i] >= 70 and age_pop[i] <= 79:
            eGFR_pop[i] = 75
            
        if gen_pop[i] == 1:
            
            if age_pop[i] >=18 and age_pop[i] <= 44:
                
                temp = np.random.choice([0, 1, 2, 3], 1, p=[0.009, 0.376, 0.386, 0.229])
                
                SBP_pop[i] = 122
                
                if temp == 0:
                    BMI_pop[i] = np.random.randint(14, 18.49 ,1)
                elif temp == 1:
                    BMI_pop[i] = np.random.randint(18.5, 25 ,1)
                elif temp == 2:
                    BMI_pop[i] = np.random.randint(25.01, 30 ,1)
                elif temp == 3:
                    BMI_pop[i] = np.random.randint(30.01, 47 ,1)
                    
            elif age_pop[i] >=45 and age_pop[i] <= 66:
                
                temp = np.random.choice([0, 1, 2, 3], 1, p=[0.001, 0.191, 0.522, 0.286])
                
                SBP_pop[i] = 126
                
                if temp == 0:
                    BMI_pop[i] = np.random.randint(14, 18.49 ,1)
                elif temp == 1:
                    BMI_pop[i] = np.random.randint(18.5, 25 ,1)
                elif temp == 2:
                    BMI_pop[i] = np.random.randint(25.01, 30 ,1)
                elif temp == 3:
                    BMI_pop[i] = np.random.randint(30.01, 47 ,1)                
                
            elif age_pop[i] >= 67:

                temp = np.random.choice([0, 1, 2, 3], 1, p=[0.003, 0.27, 0.473, 0.255])
                
                SBP_pop[i] = 140
                
                if temp == 0:
                    BMI_pop[i] = np.random.randint(14, 18.49 ,1)
                elif temp == 1:
                    BMI_pop[i] = np.random.randint(18.5, 25 ,1)
                elif temp == 2:
                    BMI_pop[i] = np.random.randint(25.01, 30 ,1)
                elif temp == 3:
                    BMI_pop[i] = np.random.randint(30.01, 47 ,1)                 
        
        elif gen_pop[i] == 0:
                
            if age_pop[i] >= 18 and age_pop[i] <= 44:
                
                temp = np.random.choice([0, 1, 2, 3], 1, p=[0.011, 0.452, 0.269, 0.268])
                
                SBP_pop[i] = 108
                
                if temp == 0:
                    BMI_pop[i] = np.random.randint(14, 18.49 ,1)
                elif temp == 1:
                    BMI_pop[i] = np.random.randint(18.5, 25 ,1)
                elif temp == 2:
                    BMI_pop[i] = np.random.randint(25.01, 30 ,1)
                elif temp == 3:
                    BMI_pop[i] = np.random.randint(30.01, 47 ,1)
                    
            elif age_pop[i] >= 45 and age_pop[i] <= 66:
                
                temp = np.random.choice([0, 1, 2, 3], 1, p=[0.002, 0.343, 0.350, 0.305])
                
                SBP_pop[i] = 120
                
                if temp == 0:
                    BMI_pop[i] = np.random.randint(14, 18.49 ,1)
                elif temp == 1:
                    BMI_pop[i] = np.random.randint(18.5, 25 ,1)
                elif temp == 2:
                    BMI_pop[i] = np.random.randint(25.01, 30 ,1)
                elif temp == 3:
                    BMI_pop[i] = np.random.randint(30.01, 47 ,1)                
                
            elif age_pop[i] >= 67:

                temp = np.random.choice([0, 1, 2, 3], 1, p=[0.015, 0.318, 0.413, 0.253])
                
                SBP_pop[i] = 140
                
                if temp == 0:
                    BMI_pop[i] = np.random.randint(14, 18.49 ,1)
                elif temp == 1:
                    BMI_pop[i] = np.random.randint(18.5, 25 ,1)
                elif temp == 2:
                    BMI_pop[i] = np.random.randint(25.01, 30 ,1)
                elif temp == 3:
                    BMI_pop[i] = np.random.randint(30.01, 47 ,1)
    
    pop = [bt_pop, cig_pop, age_pop, eGFR_pop, BMI_pop, aa_pop, SBP_pop, rel_pop, hla_b_pop, hla_dr_pop, gen_pop]
    pop = np.array(pop,dtype=object)
                
    return pop

In [254]:
def LKDPI_fun(rec_pop, don_pop):
#--------------------------------------------------------------------------------------------------------------------------
    #Function that evaluates kidney receiver and donor compatibility
    
    #Input Variables:
        #rec_pop:       Pool of kidney receivers, array
        #don_pop:       Pool of kidney donors, array
    
    #Output:
        #LKDPI:         Compatibility of each kidney receiver and donor, array
        
    #A Risk Index for Living Donor Kidney Transplantation
    #Living Kidney Donor Profile Index
    #https://onlinelibrary.wiley.com/doi/pdf/10.1111/ajt.13709
#--------------------------------------------------------------------------------------------------------------------------
    
    #Input:
    age = don_pop[2,:]                 #Age of donor
    cig = don_pop[1,:]                 #Smoker, 1 for True, 0 for False
    eGFR = don_pop[3,:]                #Estimated Glomerular Filtration Rate
    BMI = don_pop[4,:]                 #Body Mass Index
    aa = don_pop[5,:]                  #African-American, 1 for True, 0 for False
    SBP = don_pop[6,:]                 #Systolic Blood Pressure
    rel = don_pop[7,:]                 #Donor and Recipient Related, 1 for True, 0 for False
    hla_b = don_pop[8,:]               #HLA-B mismatches, 0 to 2
    hla_dr = don_pop[9,:]              #HLA-DR mismatches, 0 to 2
    
    res_g = rec_pop[10,:]              #Recipient Gender, 1 for male, 0 for female
    don_g = don_pop[10,:]              #Donor Gender, 1 for male, 0 for female
    res_w = 80                         #Recipient Weight
    don_w = 80                         #Donor Weight
    res_bt = rec_pop[0,:]              #Recipient Blood type, O, A, B or AB
    don_bt = don_pop[0,:]              #Donor Blood type, O, A, B or AB

    #Initialize:
    age_f = 0                          #Age Factor
    aa_f = 0                           #African-American Factor
    cig_f = 0                          #Cigarette Use Factor
    mm_f = 0                           #Male Recipient, Male Donor Factor
    bt_f = 0                           #Blood Type Factor
    rel_f = 0                          #Related Factor
    WR = 0                             #Weight Ratio
    LKDPI = np.zeros(shape=(rec_pop.shape[1],don_pop.shape[1])) #Output
    
    #Calculate compatibility:
    for j in range(rec_pop.shape[1]):
        
        for i in range(don_pop.shape[1]):

            if age[i] > 50:
                age_f = age[i] - 50
            else:
                age_f = 0
    
            if cig[i] == 1:
                cig_f = 14.33
            else:
                cig_f = 0
    
            if aa[i] == 1:
                aa_f = 22.34
            else:
                aa_f = 0
    
            if res_g[j] == 1 and don_g[i] == 1:
                mm_f = -21.68
            else:
                mm_f = 0

            if res_bt[j] == "A" and don_bt[i] == "O" or don_bt[i] == "A":
                bt_f = 0
            elif res_bt[j] == "B" and don_bt[i] == "O" or don_bt[i] == "B":
                bt_f = 0
            elif res_bt[j] == "AB" and don_bt[i] == "O" or don_bt[i] == "A" or don_bt[i] == "B" or don_bt[i] == "AB":
                bt_f = 0
            elif res_bt[j] == "O" and don_bt[i] == "O":
                bt_f = 0
            else:
                bt_f = 27.3
                
            if rel[i] == 0:
                rel_f = -10.16
            else:
                rel_f = 0

            if don_w/res_w < 0.9:
                WR = don_w/res_w
            else:
                WR = 0.9
                
                hla_b_temp = np.random.choice([0, 1, 2], 1, p=[0.05, 0.30, 0.65])
                hla_dr_temp = np.random.choice([0, 1, 2], 1, p=[0.05, 0.30, 0.65])
                
            #LKDPI[j,i] = -11.3+(1.85*age_f)-(0.381*eGFR[i])+(1.17*(BMI[i]+cig_f+aa_f))+(0.44*(SBP[i]+mm_f+bt_f+rel_f))+(8.57*hla_b[i])+(8.26*hla_dr[i])-(50.87*WR)
            LKDPI[j,i] = -11.3+(1.85*age_f)-(0.381*eGFR[i])+(1.17*(BMI[i]+cig_f+aa_f))+(0.44*(SBP[i]+mm_f+bt_f+rel_f))+(8.57*hla_b_temp)+(8.26*hla_dr_temp)-(50.87*WR)
            
    return LKDPI

In [1]:
def kidneyMatch(rec_pop, don_pop, don_link, LKDPI):
#--------------------------------------------------------------------------------------------------------------------------
    #Function that finds kidney receivers that provide kidney donors that are matches to other kidney receiver
    
    #Input Variables:
        #rec_pop:    Pool of kidney recievers, array
        #don_pop:    Pool of kidney donors, array
        #don_link:   List of what donors are associated with what receiver, array
        #LKDPI:      Compatability of all donors vs. receivers, array
    
    #Output:
        #rec_pop:    Pool of kidney recievers, array
        #don_pop:    Pool of kidney donors, array
        #don_link:   List of what donors are associated with what receiver, array
        #LKDPI:      Compatability of all donors vs. receivers, array
#--------------------------------------------------------------------------------------------------------------------------

    #Initialize:
    matches = np.zeros(shape=(rec_pop.shape[1],don_pop.shape[1]))
    no_match = np.zeros(rec_pop.shape[1])
    match_pop = np.zeros(shape=(rec_pop.shape[1],rec_pop.shape[1]))
    

    #Find all matches:
    for j in range(rec_pop.shape[1]):
        
        for i in range(don_pop.shape[1]):
            
            if LKDPI[j,i] <= 0:
                
                matches[j,i] = don_link[i]
                no_match[don_link[i]-1] = don_link[i]
                match_pop[don_link[i]-1,j] = 1
                
                #print(f"Kidney receiver #: {j+1} is a match to donor#: {i+1} from kidney receiver #: {don_link[i]}")
            
            else:
                
                matches[j,i] = 0
    
    
    #Remove all receivers that don't contribute a donor
    for k in range(rec_pop.shape[1]-1,-1,-1):
        
        if no_match[k] == 0:
            
            print(f"Kidney receiver #: {k+1} has no donors that are matches to other kidney receivers")
        
            LKDPI = np.delete(LKDPI,k,axis=0)
            rec_pop = np.delete(rec_pop,k,axis=1)
            matches = np.delete(matches,k,axis=0)
            match_pop = np.delete(match_pop,k,axis=0)
            match_pop = np.delete(match_pop,k,axis=1)
            
    
    #Remove all donors that are associated with receivers that don't contribute a donor
    for l in range(don_link.shape[0]-1,-1,-1):
        
        if not don_link[l] in no_match:
            
            don_link = np.delete(don_link,l,axis=0)
            don_pop = np.delete(don_pop,l,axis=1)
            LKDPI = np.delete(LKDPI,l,axis=1)
            matches = np.delete(matches,l,axis=1)
                

    return rec_pop, don_pop, don_link, LKDPI, match_pop

In [74]:
def int_starting_population(nivar, npop):
#--------------------------------------------------------------------------------------------------------------------------
    #Function for generation of initial population
    
    #Input Variables:
        #npop:      Number of Genes in Pool, int
        #nivar:     Number of Chromosomes in a Gene, int
    
    #Output:
        #Pool of Genes, array
#--------------------------------------------------------------------------------------------------------------------------
        
    #Initialize:
    Ipop = np.zeros((npop, nivar))
    
    tempGene = range(nivar)

    for i in range(npop):
        Ipop[i,:] = random.sample(tempGene,nivar) 
    return Ipop

In [76]:
def permutations(m_pop, Np, L, perm_f, rejects, pr):
#--------------------------------------------------------------------------------------------------------------------------    
    #Function that performs permutations
    
    #Input Variables:
        #m_pop: Pool of Genes, Dictionary
        #Np:    Number of Genes in Pool
        #L:    Number of Chromosomes in a Gene
        #perm_f: 
        #rejects:    List of keys for genes not optimal for reproduction
        #pr:    Print, 0 or 1
    
    #Output:
        #Pool with a New Generation of Genes
#--------------------------------------------------------------------------------------------------------------------------    
    #Pp = round(Np*perm_f)            #Number of Genes to be Permutated
    Pp = Np-perm_f                    #Number of Genes to be Permutated
    gL = list(m_pop.keys())           #List of keys for Genepool Dictionary
    new_gL = random.sample(gL, Pp)    #Genes chosen for Permutation
    p_pop = m_pop
    chrome = np.zeros(L)
    
    if pr == 1:
        print(f"Genes chosen for Permutation: {new_gL}")
    
    #Permutations, type 1, 2 or 3, randomly selected:
    for i in range(0,Pp):
        
        perm_type = random.randint(1,4)
        
        #Select Chromosomes for Permutation:
            
        #Initialize:
        perm_chrA = 0
        perm_chrB = 0
        
        while perm_chrA == perm_chrB:
    
            perm_chrA = random.randint(0,L-1)
            perm_chrB = random.randint(0,L-1)
        
            if perm_chrA > perm_chrB:
                temp = perm_chrA
                perm_chrA = perm_chrB
                perm_chrB = temp
            else:
                perm_chrA = perm_chrA
                perm_chrB = perm_chrB
            
            if pr == 1:
                print(f"Chromosome A: {perm_chrA}")
                print(f"Chromosome B: {perm_chrB}")
    
        chrome = p_pop[new_gL[i]]
        
        if pr == 1:
            print(f"Chromosomes: {chrome}")
    
        if perm_type == 1:
            
            chrome[perm_chrA:perm_chrB] = chrome[perm_chrA:perm_chrB][::-1]
            chrome = list(chrome)
            
            if pr == 1:
                print(f"Permutation type: {perm_type}")
                print(f"Chromosomes: {chrome}")
        
        elif perm_type == 2:
            
            temp_chrome1 = chrome[perm_chrA]
            temp_chrome2 = chrome[perm_chrB]
            chrome[perm_chrA] = temp_chrome2
            chrome[perm_chrB] = temp_chrome1
            chrome = list(chrome)
            
            if pr == 1:
                print(f"Permutation type: {perm_type}")
                print(f"Chromosomes: {chrome}")
            
        elif perm_type == 3:
            
            temp_chrome1 = chrome[perm_chrA]
            
            if temp_chrome1 < L:
                temp_chrome2 = chrome[perm_chrA+1]
                chrome[perm_chrA] = temp_chrome2
                chrome[perm_chrA+1] = temp_chrome1 
            else:
                temp_chrome2 = chrome[perm_chrA-1]
                chrome[perm_chrA] = temp_chrome2
                chrome[perm_chrA-1] = temp_chrome1
            
            chrome = list(chrome)
             
            if pr == 1:
                print(f"Permutation type: {perm_type}")
                print(f"Chromosomes: {chrome}")
            
        elif perm_type == 4:
            
            if perm_chrB-perm_chrA == 1:
                
                if pr == 1:
                    print("No Relocation")
                    
                chrome = list(chrome)
            else:
                temp_chrome1 = chrome[perm_chrA]
                temp_chrome2 = chrome[perm_chrB]
                temp_chrome_arr2 = chrome[perm_chrA+1:perm_chrB]
                temp_chrome_arr3 = chrome[perm_chrB:]
                
                if perm_chrA == 0:
                    chrome = [*temp_chrome_arr2, temp_chrome1, *temp_chrome_arr3]
                else:
                    temp_chrome_arr1 = chrome[0:perm_chrA]
                    chrome = [*temp_chrome_arr1, *temp_chrome_arr2, temp_chrome1, *temp_chrome_arr3]
             
                if pr == 1:
                    print("Relocation")
                    print(f"Chromosomes: {chrome}")
        
        p_pop[rejects[i]] = chrome
        
    return p_pop

In [43]:
def fitnessOne(Ipop, match_pop):
    
#Initialize
Grade = np.zeros(Ipop.shape[1])
     
for i in range(Ipop.shape[1]):

    for j in range(Ipop.shape[0]-1):

        if match_pop[Ipop[i,j]]:
    

    return Matches, Matches2


In [44]:
[Matches, Matches2] = fitness()

print(Matches)
print(Matches2)

[[0. 8. 0. 0. 0. 2. 0. 0. 0. 0. 0. 0. 0. 0. 2. 0. 8. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 5. 4. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 4.]
 [0. 8. 0. 0. 0. 2. 0. 0. 0. 0. 3. 0. 0. 0. 2. 0. 8. 0. 0. 0. 0. 8. 9. 0.
  0. 0. 0. 0. 0. 0. 5. 4. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 4.]
 [0. 8. 0. 0. 0. 2. 0. 0. 0. 0. 0. 0. 0. 0. 2. 0. 8. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 5. 4. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 4.]
 [0. 8. 0. 0. 0. 2. 0. 0. 0. 0. 0. 0. 0. 0. 2. 0. 8. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 5. 4. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 4.]
 [0. 8. 0. 0. 0. 2. 0. 0. 0. 0. 0. 0. 0. 0. 2. 0. 8. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 5. 4. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 4.]
 [0. 8. 0. 0. 0. 2. 0. 0. 0. 0. 3. 0. 0. 0. 2. 0. 8. 0. 0. 0. 0. 8. 9. 0.
  0. 0. 0. 0. 0. 0. 5. 4. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 4.]
 [0. 8. 0. 0. 0. 2. 0. 0. 0. 0. 0. 0. 0. 0. 2. 0. 8. 0. 0.

In [213]:
def objective():
    
            
    Ipop = int_starting_population(rec_size,50)

    #best = fitness(Ipop)
    
    return no_match

In [214]:
no_match = objective()

print(no_match)

Kidney receiver #: 6 has no donors that are matches to other kidney receivers
Kidney receiver #: 4 has no donors that are matches to other kidney receivers
[ 1.  2.  3.  0.  5.  0.  7.  8.  9. 10.]


In [289]:
    
    
#-------------------------------------------------------------------------------------------------------------------------    
#Preprocessing:

    rec_size = 10
    don_size = 50

    rec_pop = rand_pop(rec_size)                    #Generate a random pool of kidney receivers.
    don_pop = rand_pop(don_size)                    #Generate a random pool of kidney donors.

    #Create a random association between kidney receivers and kidney donors:
    test = np.arange(1,rec_size+1,1)
    test3 = np.ones(rec_size)*(1/rec_size)
    don_link = np.random.choice(test, don_size, p=test3)

    LKDPI = LKDPI_fun(rec_pop, don_pop)            #Find compatibility between each reciever and donor.
    
    #Find recievers that could particiapte in the kidney chain
    [rec_pop, don_pop, don_link, LKDPI, match_pop] = kidneyMatch(rec_pop, don_pop, don_link, LKDPI)
    
#-------------------------------------------------------------------------------------------------------------------------
#Initialize:    

    Ipop = int_starting_population(rec_size,50)    #Generate Inital GenePool.

#Optimize:

#Fitness:

#Permutation:
    
    
    
    print(rec_pop.shape)
    print(don_pop.shape)
    print(don_link.shape)
    print(LKDPI.shape)
    print(matches.shape)
    print(match_pop)
    
    

(11, 10)
(11, 50)
(50,)
(10, 50)
Kidney receiver #: 3 has no donors that are matches to other kidney receivers
(11, 9)
(11, 47)
(47,)
(9, 47)
(10, 50)
[[1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [1. 1. 1. 1. 1. 1. 0. 1. 1.]
 [0. 1. 1. 1. 1. 1. 0. 1. 0.]
 [0. 0. 0. 0. 1. 1. 0. 0. 1.]
 [0. 1. 1. 0. 0. 1. 0. 1. 1.]
 [0. 1. 1. 1. 1. 1. 0. 1. 0.]
 [1. 1. 1. 1. 1. 1. 0. 1. 0.]]
